#!/bin/bash

# Delete all remote branches starting with arg1
git branch -r --list origin/$1* | tr -d ' ' | \sed "s/^origin\///" | xargs -I {} git push origin --delete {}

# Delete all local branches starting with arg1
git branch --list $1*| gxargs -r git branch -d
